server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/manage_server?characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
#    password: mj725610
    password: mj725610

    jmx:
      enabled: false
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.example.manageserver.bean
logging:
  level:
    root: DEBUG
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

# src/main/resources/application.yml
commodity:
  image-dir: src/main/resources/static/images/  # 开发环境存储路径

mybatis:
  configuration:
    map-underscore-to-camel-case: true



